package edu.tamu.webtoxpi.Server.Models.Classes;
// Generated Aug 26, 2015 7:27:58 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Components generated by hbm2java
 */
@Entity
@Table(name = "components", schema = "public")
public class Components implements java.io.Serializable
{

	private int id;
	private Componentsources componentsources;
	private Types types;
	private Units units;
	private Users users;
	private String code;
	private String name;
	private Date updateddt;
	private Set<Results> resultses = new HashSet<Results>(0);

	public Components()
	{
	}

	public Components(int id, Types types, Units units, Users users, String code, Date updateddt)
	{
		this.id = id;
		this.types = types;
		this.units = units;
		this.users = users;
		this.code = code;
		this.updateddt = updateddt;
	}

	public Components(int id, Componentsources componentsources, Types types, Units units, Users users, String code, String name, Date updateddt, Set<Results> resultses)
	{
		this.id = id;
		this.componentsources = componentsources;
		this.types = types;
		this.units = units;
		this.users = users;
		this.code = code;
		this.name = name;
		this.updateddt = updateddt;
		this.resultses = resultses;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "compsource_id")
	public Componentsources getComponentsources()
	{
		return this.componentsources;
	}

	public void setComponentsources(Componentsources componentsources)
	{
		this.componentsources = componentsources;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "type_id", nullable = false)
	public Types getTypes()
	{
		return this.types;
	}

	public void setTypes(Types types)
	{
		this.types = types;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "unit", nullable = false)
	public Units getUnits()
	{
		return this.units;
	}

	public void setUnits(Units units)
	{
		this.units = units;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "updatedby", nullable = false)
	public Users getUsers()
	{
		return this.users;
	}

	public void setUsers(Users users)
	{
		this.users = users;
	}

	@Column(name = "code", nullable = false)
	public String getCode()
	{
		return this.code;
	}

	public void setCode(String code)
	{
		this.code = code;
	}

	@Column(name = "name")
	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updateddt", nullable = false, length = 29)
	public Date getUpdateddt()
	{
		return this.updateddt;
	}

	public void setUpdateddt(Date updateddt)
	{
		this.updateddt = updateddt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "components")
	public Set<Results> getResultses()
	{
		return this.resultses;
	}

	public void setResultses(Set<Results> resultses)
	{
		this.resultses = resultses;
	}

}
