package edu.tamu.webtoxpi.Server.Models.Classes;
// Generated Aug 26, 2015 7:27:58 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Importinfo generated by hbm2java
 */
@Entity
@Table(name = "importinfo", schema = "public")
public class Importinfo implements java.io.Serializable
{

	private int id;
	private Users users;
	private Date transactiondate;
	private String notes;
	private String filename;
	private Set<Orders> orderses = new HashSet<Orders>(0);

	public Importinfo()
	{
	}

	public Importinfo(int id, Users users, Date transactiondate, String notes, String filename)
	{
		this.id = id;
		this.users = users;
		this.transactiondate = transactiondate;
		this.notes = notes;
		this.filename = filename;
	}

	public Importinfo(int id, Users users, Date transactiondate, String notes, String filename, Set<Orders> orderses)
	{
		this.id = id;
		this.users = users;
		this.transactiondate = transactiondate;
		this.notes = notes;
		this.filename = filename;
		this.orderses = orderses;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public Users getUsers()
	{
		return this.users;
	}

	public void setUsers(Users users)
	{
		this.users = users;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "transactiondate", nullable = false, length = 29)
	public Date getTransactiondate()
	{
		return this.transactiondate;
	}

	public void setTransactiondate(Date transactiondate)
	{
		this.transactiondate = transactiondate;
	}

	@Column(name = "notes", nullable = false)
	public String getNotes()
	{
		return this.notes;
	}

	public void setNotes(String notes)
	{
		this.notes = notes;
	}

	@Column(name = "filename", nullable = false)
	public String getFilename()
	{
		return this.filename;
	}

	public void setFilename(String filename)
	{
		this.filename = filename;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "importinfo")
	public Set<Orders> getOrderses()
	{
		return this.orderses;
	}

	public void setOrderses(Set<Orders> orderses)
	{
		this.orderses = orderses;
	}

}
