package edu.tamu.webtoxpi.Server.Models.Classes;
// Generated Aug 26, 2015 7:27:58 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Notes generated by hbm2java
 */
@Entity
@Table(name = "notes", schema = "public")
public class Notes implements java.io.Serializable
{

	private int id;
	private Users users;
	private String code;
	private String note;
	private int ownerId;
	private Serializable ownertype;
	private boolean visible;
	private Date updateddt;

	public Notes()
	{
	}

	public Notes(int id, Users users, String code, int ownerId, Serializable ownertype, boolean visible, Date updateddt)
	{
		this.id = id;
		this.users = users;
		this.code = code;
		this.ownerId = ownerId;
		this.ownertype = ownertype;
		this.visible = visible;
		this.updateddt = updateddt;
	}

	public Notes(int id, Users users, String code, String note, int ownerId, Serializable ownertype, boolean visible, Date updateddt)
	{
		this.id = id;
		this.users = users;
		this.code = code;
		this.note = note;
		this.ownerId = ownerId;
		this.ownertype = ownertype;
		this.visible = visible;
		this.updateddt = updateddt;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "updatedby", nullable = false)
	public Users getUsers()
	{
		return this.users;
	}

	public void setUsers(Users users)
	{
		this.users = users;
	}

	@Column(name = "code", nullable = false)
	public String getCode()
	{
		return this.code;
	}

	public void setCode(String code)
	{
		this.code = code;
	}

	@Column(name = "note")
	public String getNote()
	{
		return this.note;
	}

	public void setNote(String note)
	{
		this.note = note;
	}

	@Column(name = "owner_id", nullable = false)
	public int getOwnerId()
	{
		return this.ownerId;
	}

	public void setOwnerId(int ownerId)
	{
		this.ownerId = ownerId;
	}

	@Column(name = "ownertype", nullable = false)
	public Serializable getOwnertype()
	{
		return this.ownertype;
	}

	public void setOwnertype(Serializable ownertype)
	{
		this.ownertype = ownertype;
	}

	@Column(name = "visible", nullable = false)
	public boolean isVisible()
	{
		return this.visible;
	}

	public void setVisible(boolean visible)
	{
		this.visible = visible;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updateddt", nullable = false, length = 29)
	public Date getUpdateddt()
	{
		return this.updateddt;
	}

	public void setUpdateddt(Date updateddt)
	{
		this.updateddt = updateddt;
	}

}
