package edu.tamu.webtoxpi.Server.Models.Classes;
// Generated Aug 26, 2015 7:27:58 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Types generated by hbm2java
 */
@Entity
@Table(name = "types", schema = "public")
public class Types implements java.io.Serializable
{

	private int id;
	private Groups groups;
	private Users users;
	private String code;
	private String name;
	private Date updateddt;
	private Set<Components> componentses = new HashSet<Components>(0);

	public Types()
	{
	}

	public Types(int id, Groups groups, Users users, String code, Date updateddt)
	{
		this.id = id;
		this.groups = groups;
		this.users = users;
		this.code = code;
		this.updateddt = updateddt;
	}

	public Types(int id, Groups groups, Users users, String code, String name, Date updateddt, Set<Components> componentses)
	{
		this.id = id;
		this.groups = groups;
		this.users = users;
		this.code = code;
		this.name = name;
		this.updateddt = updateddt;
		this.componentses = componentses;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "group_id", nullable = false)
	public Groups getGroups()
	{
		return this.groups;
	}

	public void setGroups(Groups groups)
	{
		this.groups = groups;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "updatedby", nullable = false)
	public Users getUsers()
	{
		return this.users;
	}

	public void setUsers(Users users)
	{
		this.users = users;
	}

	@Column(name = "code", nullable = false)
	public String getCode()
	{
		return this.code;
	}

	public void setCode(String code)
	{
		this.code = code;
	}

	@Column(name = "name")
	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updateddt", nullable = false, length = 29)
	public Date getUpdateddt()
	{
		return this.updateddt;
	}

	public void setUpdateddt(Date updateddt)
	{
		this.updateddt = updateddt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "types")
	public Set<Components> getComponentses()
	{
		return this.componentses;
	}

	public void setComponentses(Set<Components> componentses)
	{
		this.componentses = componentses;
	}

}
