package edu.tamu.webtoxpi.Server.Models.Classes;
// Generated Aug 26, 2015 7:27:58 PM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Viewtemplates generated by hbm2java
 */
@Entity
@Table(name = "viewtemplates", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "code") )
public class Viewtemplates implements java.io.Serializable
{

	private int id;
	private Users usersByUpdatedby;
	private Users usersByUserId;
	private String code;
	private Serializable objectxml;
	private Date updateddt;

	public Viewtemplates()
	{
	}

	public Viewtemplates(int id, Users usersByUpdatedby, Users usersByUserId, String code, Date updateddt)
	{
		this.id = id;
		this.usersByUpdatedby = usersByUpdatedby;
		this.usersByUserId = usersByUserId;
		this.code = code;
		this.updateddt = updateddt;
	}

	public Viewtemplates(int id, Users usersByUpdatedby, Users usersByUserId, String code, Serializable objectxml, Date updateddt)
	{
		this.id = id;
		this.usersByUpdatedby = usersByUpdatedby;
		this.usersByUserId = usersByUserId;
		this.code = code;
		this.objectxml = objectxml;
		this.updateddt = updateddt;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "updatedby", nullable = false)
	public Users getUsersByUpdatedby()
	{
		return this.usersByUpdatedby;
	}

	public void setUsersByUpdatedby(Users usersByUpdatedby)
	{
		this.usersByUpdatedby = usersByUpdatedby;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public Users getUsersByUserId()
	{
		return this.usersByUserId;
	}

	public void setUsersByUserId(Users usersByUserId)
	{
		this.usersByUserId = usersByUserId;
	}

	@Column(name = "code", unique = true, nullable = false)
	public String getCode()
	{
		return this.code;
	}

	public void setCode(String code)
	{
		this.code = code;
	}

	@Column(name = "objectxml")
	public Serializable getObjectxml()
	{
		return this.objectxml;
	}

	public void setObjectxml(Serializable objectxml)
	{
		this.objectxml = objectxml;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updateddt", nullable = false, length = 29)
	public Date getUpdateddt()
	{
		return this.updateddt;
	}

	public void setUpdateddt(Date updateddt)
	{
		this.updateddt = updateddt;
	}

}
