package edu.tamu.webtoxpi.Server.Models.Classes;
// Generated Aug 26, 2015 7:27:58 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Weights generated by hbm2java
 */
@Entity
@Table(name = "weights", schema = "public")
public class Weights implements java.io.Serializable
{

	private int id;
	private Users users;
	private String code;
	private String name;
	private int weight;
	private Date updateddt;
	private Set<Groups> groupses = new HashSet<Groups>(0);

	public Weights()
	{
	}

	public Weights(int id, Users users, String code, int weight, Date updateddt)
	{
		this.id = id;
		this.users = users;
		this.code = code;
		this.weight = weight;
		this.updateddt = updateddt;
	}

	public Weights(int id, Users users, String code, String name, int weight, Date updateddt, Set<Groups> groupses)
	{
		this.id = id;
		this.users = users;
		this.code = code;
		this.name = name;
		this.weight = weight;
		this.updateddt = updateddt;
		this.groupses = groupses;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "updatedby", nullable = false)
	public Users getUsers()
	{
		return this.users;
	}

	public void setUsers(Users users)
	{
		this.users = users;
	}

	@Column(name = "code", nullable = false)
	public String getCode()
	{
		return this.code;
	}

	public void setCode(String code)
	{
		this.code = code;
	}

	@Column(name = "name")
	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	@Column(name = "weight", nullable = false)
	public int getWeight()
	{
		return this.weight;
	}

	public void setWeight(int weight)
	{
		this.weight = weight;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updateddt", nullable = false, length = 29)
	public Date getUpdateddt()
	{
		return this.updateddt;
	}

	public void setUpdateddt(Date updateddt)
	{
		this.updateddt = updateddt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "weights")
	public Set<Groups> getGroupses()
	{
		return this.groupses;
	}

	public void setGroupses(Set<Groups> groupses)
	{
		this.groupses = groupses;
	}

}
